// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: garden.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GardenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GardenName      string                 `protobuf:"bytes,1,opt,name=GardenName,proto3" json:"GardenName,omitempty"`
	GardenCapacity  float64                `protobuf:"fixed64,2,opt,name=GardenCapacity,proto3" json:"GardenCapacity,omitempty"`
	GardenRentPrice float64                `protobuf:"fixed64,3,opt,name=GardenRentPrice,proto3" json:"GardenRentPrice,omitempty"`
	OwnerID         string                 `protobuf:"bytes,4,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GardenRequest) Reset() {
	*x = GardenRequest{}
	mi := &file_garden_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GardenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GardenRequest) ProtoMessage() {}

func (x *GardenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garden_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GardenRequest.ProtoReflect.Descriptor instead.
func (*GardenRequest) Descriptor() ([]byte, []int) {
	return file_garden_proto_rawDescGZIP(), []int{0}
}

func (x *GardenRequest) GetGardenName() string {
	if x != nil {
		return x.GardenName
	}
	return ""
}

func (x *GardenRequest) GetGardenCapacity() float64 {
	if x != nil {
		return x.GardenCapacity
	}
	return 0
}

func (x *GardenRequest) GetGardenRentPrice() float64 {
	if x != nil {
		return x.GardenRentPrice
	}
	return 0
}

func (x *GardenRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

type GardenResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResponseCode   string                 `protobuf:"bytes,1,opt,name=ResponseCode,proto3" json:"ResponseCode,omitempty"`
	GardenID       string                 `protobuf:"bytes,2,opt,name=GardenID,proto3" json:"GardenID,omitempty"`
	GardenName     string                 `protobuf:"bytes,3,opt,name=GardenName,proto3" json:"GardenName,omitempty"`
	GardenPrice    string                 `protobuf:"bytes,4,opt,name=GardenPrice,proto3" json:"GardenPrice,omitempty"`
	GardenCapacity string                 `protobuf:"bytes,5,opt,name=GardenCapacity,proto3" json:"GardenCapacity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GardenResponse) Reset() {
	*x = GardenResponse{}
	mi := &file_garden_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GardenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GardenResponse) ProtoMessage() {}

func (x *GardenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garden_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GardenResponse.ProtoReflect.Descriptor instead.
func (*GardenResponse) Descriptor() ([]byte, []int) {
	return file_garden_proto_rawDescGZIP(), []int{1}
}

func (x *GardenResponse) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *GardenResponse) GetGardenID() string {
	if x != nil {
		return x.GardenID
	}
	return ""
}

func (x *GardenResponse) GetGardenName() string {
	if x != nil {
		return x.GardenName
	}
	return ""
}

func (x *GardenResponse) GetGardenPrice() string {
	if x != nil {
		return x.GardenPrice
	}
	return ""
}

func (x *GardenResponse) GetGardenCapacity() string {
	if x != nil {
		return x.GardenCapacity
	}
	return ""
}

var File_garden_proto protoreflect.FileDescriptor

const file_garden_proto_rawDesc = "" +
	"\n" +
	"\fgarden.proto\x12\x06garden\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n" +
	"\rGardenRequest\x12\x1e\n" +
	"\n" +
	"GardenName\x18\x01 \x01(\tR\n" +
	"GardenName\x12&\n" +
	"\x0eGardenCapacity\x18\x02 \x01(\x01R\x0eGardenCapacity\x12(\n" +
	"\x0fGardenRentPrice\x18\x03 \x01(\x01R\x0fGardenRentPrice\x12\x18\n" +
	"\aOwnerID\x18\x04 \x01(\tR\aOwnerID\"\xba\x01\n" +
	"\x0eGardenResponse\x12\"\n" +
	"\fResponseCode\x18\x01 \x01(\tR\fResponseCode\x12\x1a\n" +
	"\bGardenID\x18\x02 \x01(\tR\bGardenID\x12\x1e\n" +
	"\n" +
	"GardenName\x18\x03 \x01(\tR\n" +
	"GardenName\x12 \n" +
	"\vGardenPrice\x18\x04 \x01(\tR\vGardenPrice\x12&\n" +
	"\x0eGardenCapacity\x18\x05 \x01(\tR\x0eGardenCapacity2\xca\x01\n" +
	"\vAuthService\x12=\n" +
	"\fCreateGarden\x12\x15.garden.GardenRequest\x1a\x16.garden.GardenResponse\x12=\n" +
	"\fUpdateGarden\x12\x15.garden.GardenRequest\x1a\x16.garden.GardenResponse\x12=\n" +
	"\fDeleteGarden\x12\x15.garden.GardenRequest\x1a\x16.garden.GardenResponseB*Z(github.com/raihan-faza/rent-my-garden/pbb\x06proto3"

var (
	file_garden_proto_rawDescOnce sync.Once
	file_garden_proto_rawDescData []byte
)

func file_garden_proto_rawDescGZIP() []byte {
	file_garden_proto_rawDescOnce.Do(func() {
		file_garden_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garden_proto_rawDesc), len(file_garden_proto_rawDesc)))
	})
	return file_garden_proto_rawDescData
}

var file_garden_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_garden_proto_goTypes = []any{
	(*GardenRequest)(nil),  // 0: garden.GardenRequest
	(*GardenResponse)(nil), // 1: garden.GardenResponse
}
var file_garden_proto_depIdxs = []int32{
	0, // 0: garden.AuthService.CreateGarden:input_type -> garden.GardenRequest
	0, // 1: garden.AuthService.UpdateGarden:input_type -> garden.GardenRequest
	0, // 2: garden.AuthService.DeleteGarden:input_type -> garden.GardenRequest
	1, // 3: garden.AuthService.CreateGarden:output_type -> garden.GardenResponse
	1, // 4: garden.AuthService.UpdateGarden:output_type -> garden.GardenResponse
	1, // 5: garden.AuthService.DeleteGarden:output_type -> garden.GardenResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_garden_proto_init() }
func file_garden_proto_init() {
	if File_garden_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garden_proto_rawDesc), len(file_garden_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_garden_proto_goTypes,
		DependencyIndexes: file_garden_proto_depIdxs,
		MessageInfos:      file_garden_proto_msgTypes,
	}.Build()
	File_garden_proto = out.File
	file_garden_proto_goTypes = nil
	file_garden_proto_depIdxs = nil
}
